# -*- coding: utf-8 -*-
"""Deep Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19oMIs_dNri9m-XJ51qGKrSvuVSvLIQz_

# 5 Feature Selection

Because lag, rolling, momentum, and volatility features introduced missing values at the beginning of the dataset, we need to remove those incomplete rows so every feature has valid values.
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

upload = files.upload()

df_clean = pd.read_csv('Engineered_Dataset.csv')
df_clean.shape

# ===========================================
# Remove Missing Values After Feature Engineering
# ===========================================

# Shape before removing missing values
print("Shape before:", df_clean.shape)

# Remove rows with missing values
df_model = df_clean.dropna().reset_index(drop=True)

# Shape after removing missing values
print("Shape after :", df_model.shape)

# Verify that no missing values remain
print("\nRemaining Missing Values:")
print(df_model.isnull().sum().sum())

# Display dataset information
df_model.info()

"""# One Importance Notice!!

Since we are *forecasting ETF prices using an Attention-Enhanced LSTM* using the close price as our tagret the we have to shift the current Closing price to one day ahead as Target to correctly capture one day future prediction.
"""

# ===========================================
# Create Next-Day Prediction Target
# ===========================================

df_model["Target_Close"] = (
    df_model["Closing Price - VWAP (GH¢)"]
    .shift(-1)
)

# Remove the last row (no future target available)
df_model = df_model.dropna().reset_index(drop=True)

df_model.head()

print(df_model.shape)

df_model[[
    "Daily Date",
    "Closing Price - VWAP (GH¢)",
    "Target_Close"
]].tail()

# ===========================================
# 5.1 Correlation Matrix
# ===========================================

# Select only numerical columns
numeric_df = df_model.select_dtypes(include=['number'])

# Compute correlation matrix
corr_matrix = numeric_df.corr()

corr_matrix.round(3)

# ===========================================
# Correlation Heatmap
# ===========================================

plt.figure(figsize=(22,18))

sns.heatmap(
    corr_matrix,
    cmap='coolwarm',
    center=0,
    linewidths=0.3
)

plt.title("Correlation Matrix of Engineered Features", fontsize=18)

plt.show()

# ===========================================
# Correlation with Target
# ===========================================

target_corr = (
    corr_matrix["Target_Close"]
    .sort_values(ascending=False)
)

target_corr

# ===========================================
# Top Correlated Features
# ===========================================

top_corr = target_corr.drop(
    "Target_Close"
).head(20)

plt.figure(figsize=(10,8))

top_corr.sort_values().plot(
    kind='barh',
    color='steelblue'
)

plt.xlabel("Correlation Coefficient")
plt.title("Top 20 Features Correlated with Closing Price")

plt.grid(axis='x')

plt.show()

# ===========================================
# Highly Correlated Features
# ===========================================

corr_pairs = (
    corr_matrix.abs()
    .unstack()
    .sort_values(ascending=False)
)

corr_pairs = corr_pairs[
    corr_pairs < 1
]

high_corr = corr_pairs[
    corr_pairs > 0.95
]

high_corr.head(50)

"""# 5.1 Correlation Analysis

## Observation

A correlation analysis was performed to examine the relationships between the engineered predictor variables and the forecasting target, **Target_Close**, representing the next trading day's closing price. The results indicate that historical price variables exhibit the strongest linear relationships with the target. In particular, the **Last Transaction Price**, **Closing Price - VWAP**, **Opening Price**, and **Previous Closing Price** recorded correlation coefficients greater than 0.99, demonstrating that the most recent market prices are highly informative for forecasting the subsequent trading day's closing price.

Among the engineered features, lagged closing prices, moving averages (MA7, MA14, and MA30), exponential moving averages (EMA12 and EMA26), Bollinger Bands, and rolling minimum and maximum prices also exhibited very strong positive correlations with the target variable. In contrast, trading volume, return-based indicators, and calendar-related variables showed relatively weaker correlations, indicating that they contribute additional contextual information rather than serving as primary predictors.

---

## Interpretation

The correlation analysis confirms that **recent historical price information is the strongest predictor of the next trading day's closing price**, reflecting the temporal continuity commonly observed in financial time-series data. The strong relationships observed among lagged prices, moving averages, and exponential moving averages indicate that these engineered features successfully capture short-term and medium-term market trends that are relevant for forecasting future prices.

Although several predictors exhibit substantial correlations with one another, these relationships are expected because many technical indicators are derived from the same underlying price series. Rather than indicating a flaw in the feature engineering process, the high correlations demonstrate that the engineered variables effectively represent different aspects of historical market behaviour. These findings provide an initial assessment of predictor relevance and will be complemented by Variance Inflation Factor (VIF) analysis and Random Forest feature importance before determining the final feature set for the proposed Attention-LSTM forecasting model.

#5.2 Variance Inflation Factor (VIF)
Objective

While correlation measures the relationship between two variables, VIF measures how much the variance of a predictor is inflated because of its relationship with all the other predictors. This provides a more comprehensive assessment of multicollinearity.

Since our dataset contains many engineered variables derived from historical prices, high VIF values are expected. However, the analysis will help identify redundant predictors and guide feature selection.
"""

# ===========================================
# 5.2 Variance Inflation Factor (VIF)
# ===========================================

from statsmodels.stats.outliers_influence import variance_inflation_factor

# ===========================================
# Prepare Predictor Variables
# ===========================================
'''
The droped column are non numeric and not intednded as predictors
'''

X_vif = df_model.drop(columns=[
    "Daily Date",
    "Share Code",
    "Month_Name",
    "Target_Close",

])

X_vif.head()

# ===========================================
# Calculate VIF
# ===========================================

vif = pd.DataFrame()

vif["Feature"] = X_vif.columns

vif["VIF"] = [
    variance_inflation_factor(X_vif.values, i)
    for i in range(X_vif.shape[1])
]

vif = vif.sort_values("VIF", ascending=False)

vif

# ===========================================
# Top 20 Highest VIF
# ===========================================

top_vif = vif.head(20)

plt.figure(figsize=(10,8))

plt.barh(
    top_vif["Feature"],
    top_vif["VIF"],
    color="darkorange"
)

plt.xlabel("Variance Inflation Factor")
plt.title("Top 20 Features with Highest VIF")

plt.gca().invert_yaxis()

plt.grid(axis="x")

plt.show()

# ===========================================
# VIF Categories
# ===========================================

def classify_vif(value):
    if value < 5:
        return "Low"
    elif value < 10:
        return "Moderate"
    else:
        return "High"

vif["Category"] = vif["VIF"].apply(classify_vif)

vif

"""# 5.2 Variance Inflation Factor (VIF)

## Observation

Variance Inflation Factor (VIF) analysis was conducted using the predictor variables for forecasting the next trading day's closing price (`Target_Close`). The target variable was excluded from the analysis, while all historical price variables and engineered technical indicators were retained as predictors.

The analysis revealed substantial multicollinearity among several price-based variables and engineered technical indicators. In particular, the current day's **Closing Price - VWAP (GH¢)**, **EMA12**, **EMA26**, **Close_Lag7**, and the Bollinger Band indicators exhibited extremely large or infinite VIF values. Similarly, moving averages, lagged prices, and MACD-related features produced exceptionally high VIF values, reflecting the strong dependence among variables derived from the same historical price series.

Conversely, variables such as **Price Change**, **Day_of_Week**, **Total Shares Traded**, and the lagged trading volume variables displayed comparatively low VIF values, indicating relatively weak multicollinearity with the remaining predictors.

---

## Interpretation

The high VIF values are expected because many of the engineered features are mathematically derived from the historical closing price and therefore contain overlapping information. Moving averages, exponential moving averages, Bollinger Bands, lagged prices, and MACD indicators are all constructed from the same underlying price sequence, naturally resulting in strong multicollinearity.

Importantly, the presence of high multicollinearity does not invalidate these predictors for the proposed Attention-LSTM model. Unlike traditional linear regression models, sequence-based deep learning architectures are designed to learn complex nonlinear relationships from correlated temporal features. Consequently, the VIF analysis is used to identify redundancy rather than as the sole criterion for feature elimination.

The VIF results therefore complement the correlation analysis by confirming the expected dependence among technical indicators while supporting the retention of informative temporal features for next-day stock price forecasting. Final feature selection will be guided by the combined evidence from correlation analysis, VIF assessment, and Random Forest feature importance.

#5.3 Random Forest Feature Importance

Unlike correlation and VIF, which examine relationships among variables, Random Forest evaluates how much each feature actually contributes to predicting the target variable. This makes it particularly valuable for identifying informative predictors in a nonlinear setting.
"""

# ===========================================
# 5.3 Random Forest Feature Importance
# ===========================================

from sklearn.ensemble import RandomForestRegressor

# Predictor variables
X = df_model.drop(columns=[
    "Daily Date",
    "Share Code",
    "Month_Name",
    "Target_Close"
])

# Target variable
y = df_model["Target_Close"]

print(X.shape)
print(y.shape)

# ===========================================
# Train Random Forest
# ===========================================

rf = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X, y)

# ===========================================
# Feature Importance
# ===========================================

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    "Importance",
    ascending=False
)

importance

# ===========================================
# Top 20 Features
# ===========================================

top20 = importance.head(20)

plt.figure(figsize=(10,8))

plt.barh(
    top20["Feature"],
    top20["Importance"],
    color="forestgreen"
)

plt.gca().invert_yaxis()

plt.xlabel("Importance Score")
plt.title("Top 20 Random Forest Feature Importance")

plt.grid(axis="x")

plt.show()

importance["Importance (%)"] = (
    importance["Importance"] * 100
)

importance.head(20)

"""# 5.3 Random Forest Feature Importance

## Observation

A Random Forest Regressor was trained using the engineered predictor variables to estimate their relative importance for forecasting the **next trading day's closing price (`Target_Close`)**. The resulting feature importance scores indicate that the **Lower Bollinger Band (BB_Lower)** is the most influential predictor, contributing approximately **32.45%** of the model's predictive importance. Other highly ranked predictors include **MA7**, **EMA26**, **MA14**, **Year High**, **Closing Price - VWAP**, **MA30**, **MIN7**, **EMA12**, and **Last Transaction Price**, all of which represent historical price trends and technical market indicators.

Several lagged price variables, including **Close_Lag1**, **Close_Lag3**, **Close_Lag5**, **Open_Lag1**, and **Open_Lag3**, also demonstrated meaningful predictive contributions, confirming that recent trading history contains valuable information for forecasting future prices. In contrast, calendar variables, trading volume variables, return-based indicators, and momentum measures exhibited relatively low importance scores, suggesting that they play a comparatively minor role in predicting the next trading day's closing price.

---

## Interpretation

The Random Forest feature importance analysis demonstrates that **technical indicators derived from historical price movements are more informative for forecasting the next trading day's closing price than raw trading activity or calendar-based variables**. Indicators such as Bollinger Bands, moving averages, exponential moving averages, and lagged prices effectively capture short-term market trends, price momentum, and support-resistance behaviour that influence subsequent price movements.

The relatively lower importance assigned to trading volume, return-based indicators, and calendar features suggests that these variables provide complementary contextual information rather than serving as primary forecasting signals. Importantly, the feature importance rankings differ from those obtained when predicting the current day's closing price, highlighting the effect of reformulating the problem as a genuine one-step-ahead forecasting task.

The Random Forest results therefore provide an objective ranking of predictor relevance for next-day stock price forecasting and, together with the correlation and VIF analyses, form the basis for selecting the final predictor set used to train the proposed Attention-Enhanced Long Short-Term Memory (Attention-LSTM) model.

---
"""

